/** Display titles keyed by flashcard folder slug (from Obsidian index). */
export const CHAPTER_TITLES: Record<string, string> = {
  'samuel-1-2-ana-samuel-y-eli': '1 Samuel 1–2 — Ana, Samuel y Elí',
  'samuel-3-4-llamado-y-arca': '1 Samuel 3–4 — Llamado de Samuel y el arca',
  'samuel-5-7-arca-y-regreso': '1 Samuel 5–7 — El arca y el regreso a Israel',
  'samuel-8-10-israel-pide-rey': '1 Samuel 8–10 — Israel pide un rey',
  'samuel-11-saul-libera-jabes': '1 Samuel 11 — Saúl libera a Jabes',
  'samuel-12-samuel-se-despide': '1 Samuel 12 — Samuel se despide como juez',
  'samuel-13-sacrificio-de-saul': '1 Samuel 13 — El sacrificio de Saúl',
  'samuel-14-jonathan-y-los-filisteos': '1 Samuel 14 — Jonatán y los filisteos',
  'samuel-15-saul-y-los-amalecitas': '1 Samuel 15 — Saúl y los amalecitas',
  'samuel-16-david-ungeido': '1 Samuel 16 — David ungido',
  'samuel-17-david-y-goliat': '1 Samuel 17 — David y Goliat',
  'samuel-18-saul-y-david': '1 Samuel 18 — Saúl y David',
  'samuel-19-david-huye-de-saul': '1 Samuel 19 — David huye de Saúl',
  'samuel-20-jonathan-y-david': '1 Samuel 20 — Jonatán y David',
  'samuel-21-david-en-nob-y-gat': '1 Samuel 21 — David en Nob y Gat',
  'samuel-22-cueva-de-adulam': '1 Samuel 22 — Cueva de Adulam',
  '2-samuel-1-david-ante-la-muerte-de-saul': '2 Samuel 1 — David recibe la noticia de Saúl',
  '2-samuel-2-david-rey-de-juda': '2 Samuel 2 — David rey de Judá',
  '2-samuel-3-abner-y-joab': '2 Samuel 3 — Abner y Joab',
  '2-samuel-4-is-boset-y-el-reino-unido': '2 Samuel 4 — Is-boset y el reino unido',
  '2-samuel-5-david-toma-jerusalen': '2 Samuel 5 — David toma Jerusalén',
  '2-samuel-6-el-arca-en-jerusalen': '2 Samuel 6 — El arca en Jerusalén',
  '2-samuel-7-pacto-con-david': '2 Samuel 7 — Pacto con David',
  '2-samuel-8-victorias-de-david': '2 Samuel 8 — Victorias de David',
  '2-samuel-9-mefiboset': '2 Samuel 9 — Mefiboset',
  '2-samuel-10-guerra-con-los-amonitas': '2 Samuel 10 — Guerra con los amonitas',
  '2-samuel-11-david-y-betsabe': '2 Samuel 11 — David y Betsabé',
  '2-samuel-12-natan-confronta-a-david': '2 Samuel 12 — Natán confronta a David',
  '2-samuel-13-amnon-y-tamar': '2 Samuel 13 — Amnón y Tamar',
  '2-samuel-14-absalon-regresa': '2 Samuel 14 — Absalón regresa',
  '2-samuel-15-conspiracion-de-absalon': '2 Samuel 15 — Conspiración de Absalón',
  '2-samuel-16-david-huye-simei': '2 Samuel 16 — David huye; Simei',
  '2-samuel-17-ahitofel-y-husai': '2 Samuel 17 — Ahitofel y Husai',
  '2-samuel-18-muerte-de-absalon': '2 Samuel 18 — Muerte de Absalón',
  '2-samuel-19-david-regresa': '2 Samuel 19 — David regresa',
  '2-samuel-20-rebelion-de-seba': '2 Samuel 20 — Rebelión de Seba',
  '2-samuel-21-gabaonitas-y-gigantes': '2 Samuel 21 — Gabaonitas y gigantes',
  '2-samuel-22-cantico-de-david': '2 Samuel 22 — Cántico de David',
  '2-samuel-23-valientes-de-david': '2 Samuel 23 — Valientes de David',
  '2-samuel-24-censo-y-plaga': '2 Samuel 24 — Censo y plaga',
  '1-reyes-1-adolonias-y-salomon': '1 Reyes 1 — Adonías y Salomón',
  '1-reyes-2-muerte-de-david': '1 Reyes 2 — Encargos de David y muerte',
  '1-reyes-3-sabiduria-de-salomon': '1 Reyes 3 — Sabiduría de Salomón',
  '1-reyes-4-oficiales-y-prosperidad': '1 Reyes 4 — Oficiales y prosperidad',
  '1-reyes-5-hiram-y-la-madera': '1 Reyes 5 — Hiram y los preparativos del templo',
  '1-reyes-6-construccion-del-templo': '1 Reyes 6 — Construcción del templo',
  '1-reyes-7-palacio-y-ajuares': '1 Reyes 7 — Palacio y ajuares del templo',
  '1-reyes-8-dedicacion-del-templo': '1 Reyes 8 — Dedicación del templo',
  '1-reyes-9-pacto-y-ciudades': '1 Reyes 9 — Pacto, Hiram y ciudades',
  '1-reyes-10-reina-de-saba': '1 Reyes 10 — La reina de Sabá',
  '1-reyes-11-esposas-y-adversarios': '1 Reyes 11 — Esposas extranjeras y adversarios',
  '1-reyes-12-division-del-reino': '1 Reyes 12 — División del reino',
  '1-reyes-13-hombre-de-dios': '1 Reyes 13 — El hombre de Dios de Judá',
  '1-reyes-14-abias-y-roboam': '1 Reyes 14 — Abías, Jeroboam y Roboam',
  '1-reyes-15-asa-y-baasa': '1 Reyes 15 — Abiam, Asa, Nadab y Baasa',
  '1-reyes-16-omri-y-acab': '1 Reyes 16 — Elá, Zimri, Omri y Acab',
  '1-reyes-17-elias-y-la-viuda': '1 Reyes 17 — Elías y la viuda de Sarepta',
  '1-reyes-18-carmelo': '1 Reyes 18 — Elías en el Carmelo',
  '1-reyes-19-horeb-y-eliseo': '1 Reyes 19 — Elías en Horeb y el llamado de Eliseo',
  '1-reyes-20-ben-adad': '1 Reyes 20 — Ben-adad y Acab',
  '1-reyes-21-nabot': '1 Reyes 21 — La viña de Nabot',
  '1-reyes-22-miqueas-y-la-muerte-de-acab': '1 Reyes 22 — Miqueas y la muerte de Acab',
  '2-reyes-1-ocozias': '2 Reyes 1 — Ocozías y el fuego del cielo',
  '2-reyes-2-elias-es-llevado': '2 Reyes 2 — Elías es llevado y Eliseo',
  '2-reyes-3-guerra-contra-moab': '2 Reyes 3 — Guerra contra Moab',
  '2-reyes-4-milagros-de-eliseo': '2 Reyes 4 — Milagros de Eliseo',
  '2-reyes-5-naaman': '2 Reyes 5 — Naamán',
  '2-reyes-6-el-hacha-y-dotan': '2 Reyes 6 — El hacha, Dotán y el sitio',
  '2-reyes-7-el-sitio-se-levanta': '2 Reyes 7 — Se levanta el sitio de Samaria',
  '2-reyes-8-hazael-y-joram': '2 Reyes 8 — La sunamita, Hazael y Joram',
  '2-reyes-9-jehu': '2 Reyes 9 — Jehú ungido',
  '2-reyes-10-casa-de-acab-y-baal': '2 Reyes 10 — Casa de Acab y Baal',
  '2-reyes-11-atalia-y-joas': '2 Reyes 11 — Atalía y Joás',
  '2-reyes-12-joas-y-el-templo': '2 Reyes 12 — Joás repara el templo',
  '2-reyes-13-joacaz-y-elisa': '2 Reyes 13 — Joacaz, Joás de Israel y Eliseo',
  '2-reyes-14-amazias-y-jeroboam': '2 Reyes 14 — Amasías y Jeroboam II',
  '2-reyes-15-uzias-a-pecaj': '2 Reyes 15 — Azarías, Zacarías y los reyes de Israel',
  '2-reyes-16-acaz': '2 Reyes 16 — Acaz de Judá',
  '2-reyes-17-caida-de-samaria': '2 Reyes 17 — Caída de Samaria',
  '2-reyes-18-ezequias': '2 Reyes 18 — Ezequías y Senaquerib',
  '2-reyes-19-isaias-y-asiria': '2 Reyes 19 — Isaías y la liberación',
  '2-reyes-20-enfermedad-de-ezequias': '2 Reyes 20 — Enfermedad de Ezequías y Babilonia',
  '2-reyes-21-manases-y-amon': '2 Reyes 21 — Manasés y Amón',
  '2-reyes-22-josias-y-el-libro': '2 Reyes 22 — Josías y el libro de la ley',
  '2-reyes-23-reforma-y-muerte-de-josias': '2 Reyes 23 — Reforma y muerte de Josías',
  '2-reyes-24-joacim-y-el-destierro': '2 Reyes 24 — Joacim, Joaquín y el primer destierro',
  '2-reyes-25-caida-de-jerusalen': '2 Reyes 25 — Caída de Jerusalén',
}

export function chapterSlugFromPath(filePath: string): string {
  const parts = filePath.split('/')
  return parts.length > 1 ? parts[0] : 'sin-capitulo'
}

export function chapterTitle(slug: string, footerLabel?: string): string {
  if (footerLabel) return footerLabel
  return CHAPTER_TITLES[slug] ?? slug.replace(/-/g, ' ')
}
